name: HISS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Stable Ubuntu LTS version for older NDK structures

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Compilation Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        export PIP_BREAK_SYSTEM_PACKAGES=1
        pip3 install --upgrade pip setuptools virtualenv "Cython<3.0.0"

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: master
        command: export PIP_BREAK_SYSTEM_PACKAGES=1; buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SentinelMobile-APK
        path: ${{ steps.buildozer.outputs.filename }}